### ISSUE TITLE
basic example

### ISSUE THREAD

**Issue by samfultonschool** [BeTomorrow/ReImproveJS#12]
Hey, so I am just trying to get a basic example working that can tell if a number is even or odd. I have tried running multiple examples but can't seem to get them working. Just wanted to ask if someone here could help me out with a basic working example. Thanks!

**Comment by Pravez** [comment]
Hey,

Actually there is not concrete working example and I am trying right now to create one to help people getting into the library. I must say that the library needs work and is not fully finished for now, even if I try my best to enhance it quickly !

I will release soon a new version with examples and better understanding of the whole process.
Sorry for the delay,

**Comment by samfultonschool** [comment]
Oh okay, thanks for your hard work!
